### PR TITLE
fix(identity-keys): ensure CACAO `domain` value is only the keyserver host

### LINKED ISSUE #128: bug: identity keys domain should be host without protocol or path
I will begin to validate these fields in notify server soon

https://github.com/WalletConnect/walletconnect-utils/blob/f2222ea434be082ab915cb9936e00b636de8fbe7/misc/identity-keys/src/identity-keys.ts#L77

https://specs.walletconnect.com/2.0/specs/servers/keys/identity-keys#message-format

> Domain = keys.walletconnect.com
> URI = https://keys.walletconnect.com/

### PR DESCRIPTION
**Pull request by bkrem**
Resolves #128

### CODE REVIEW

File: misc/identity-keys/src/identity-keys.ts [hunk 1]
```diff
@@ -66,15 +66,16 @@ export class IdentityKeys implements IIdentityKeys {
...
 
         const cacao: Cacao = {
           h: {
             t: "eip4361",
           },
           p: {
             aud: this.keyserverUrl,
-            statement: "Test",
-            domain: this.keyserverUrl,
+            statement: `${domain} wants you to sign in with your account: ${accountId}`,
```
Comment (chris13524) [inline misc/identity-keys/src/identity-keys.ts:77]: Not really the right statement. This is redundant and is already added [here](https://github.com/WalletConnect/walletconnect-utils/blob/a2f9327d79e02cd5f7c6eed9f5ecb51679f417a5/misc/cacao/src/utils.ts#L37).

Maybe should be `""` to match identity keys spec?

```suggestion
            statement: "",
```

File: misc/identity-keys/src/identity-keys.ts [hunk 2]
```diff
@@ -66,15 +66,16 @@ export class IdentityKeys implements IIdentityKeys {
       try {
         const [pubKeyHex, privKeyHex] = await this.generateIdentityKey();
         const didKey = encodeEd25519Key(pubKeyHex);
+        const domain = new URL(this.keyserverUrl).host;
```
Comment (chris13524) [inline misc/identity-keys/src/identity-keys.ts:69]: Since working with `URL` already, would be nice to add the port number here if non-default like I did over [here](https://github.com/WalletConnect/notify-server/pull/65/files#diff-eb771f54a1fdc1c330a82981d7d27d1202a5cbe3a59581ff67af5e3361f5f90eR180-R187).

**Review by chris13524 — CHANGES_REQUESTED** [review]

File: misc/identity-keys/src/identity-keys.ts (hunk 2 above)
Comment (bkrem) [reply misc/identity-keys/src/identity-keys.ts:69]: `URL().host` includes the port number if non standard: https://developer.mozilla.org/en-US/docs/Web/API/URL

Hence chose `host` over `hostname` (which does not include port)

**Review by chris13524 — APPROVED** [review]
